### ISSUE TITLE
Wrong interpretation for "put all yellow objects under a red object under an red box"

### ISSUE THREAD

**Issue by TomyRO** [patriques82/shrdlite-course-project#13]
The interpretation is: (0) under(a,l) & under(i,l)
which doesn't take into account all the yellow objects, and all the relations between them

It's in a complex world

**Comment by patriques82** [comment]
How do you mean the output should be, so I can understand more clearly?

**Comment by TomyRO** [comment]
If you run that command on the complex world, you will see that there's a yellow box which is not taken into account for some reason

**Comment by patriques82** [comment]
I looked into it, but it is actually not wrong :-). The objects that get returned correspond to the case: "put (all yellow objects under a red object) under (an red box)" meaning "the yellow objects that are under a red object". Those objects are actually the yellow pyramid and the yellow box. The last yellow object, the yellow box, is not taken into consideration since its not under a red object.
